services:
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
